# -*- coding: utf-8 -*-
"""pipeline_etl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/166CAiu8XwabIFsryU6pg4Qdq8UJiFEgH

## **E**xtract
"""

import json
import pandas as pd
import requests

sdw2023_api_url = 'https://sdw-2023-prd.up.railway.app'
df =  pd.read_csv('SDW2023.csv')
user_ids = df['UserID'].tolist()

def get_user(id:str):
    response = requests.get(f"{sdw2023_api_url}/users/{id}")
    if response.status_code == requests.codes.ok:
        return response.json()
    return None

users = [user for id in user_ids if (user := get_user(id)) is not None]

print(users)

"""## **T**ransform"""

def generate_lorem(user:str):
    paragraphs = '2'
    api_url = 'https://api.api-ninjas.com/v1/loremipsum?paragraphs=1'
    api_key = 'g/jgy+5tZycDuVqnX0RcNQ==fC7y8iPVzO2GxQfg'
    response = requests.get(api_url,
                            headers={'X-Api-Key': api_key})
    if response.status_code == requests.codes.ok:
        return response.json().get('text').replace('\n', '')


for user in users:
    user['news'].append(dict(icon='https://digitalinnovationone.github.io/santander-dev-week-2023-api/icons/credit.svg',
                             description=generate_lorem(user)))
    print(user.get('news'))

"""## **L**oad"""

def update_user(user):
    response = requests.put(f"{sdw2023_api_url}/users/{user['id']}", json=user)
    if response.status_code == 200:
        return f"{user.get('name')} updated"
    else:
        return dict(code=response.status_code,
                    error=response.text)


for user in users:
    print(update_user(user))